###

POST http://localhost:8000/user
Content-Type: application/json

{
    "name":"Bayar",
    "isAdmin":true,
    "username":"bayar0205",
    "password":"Bayar123"
}

###
GET http://localhost:8000/user

###
DELETE http://localhost:8000/user/35d8b43d-7959-482f-9e99-488bc2fcf320


###
PUT http://localhost:8000/user/ac7e1570-a706-42d9-9df2-75192a4a352c
Content-Type: application/json

{"name":""}